version: "3.8"

services:
  shinyapp:
    image: ghcr.io/predictiveecology/wbi_shiny/shiny-wbi_nwt:v2
    restart: always
    expose:
      - "8080"
  caddy:
    image: caddy:2.6.4-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /media/data/content:/srv
      - $PWD/log:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - shinyapp
    environment:
      # - HOST="wbi.predictiveecology.org"
      - HOST=":80"
volumes:
  caddy_data:
  caddy_config:

