default:
  golem_name: ShinyWBI
  golem_version: 0.0.1
  app_prod: no
  app_baseurl: "https://wbi.predictiveecology.org/"
  app_geotiff: yes
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
