name: 'Build and Push WBI NWT App'

on:
  push:
    branches:
      - main

jobs:

  build-and-push-nwt:
    name: Build and Push Docker Image for WBI NWT Shiny App
    if: "contains(github.event.head_commit.message, 'build wbi_nwt')"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Build and push'
      uses: docker/build-push-action@v4
      with:
        context: ./03-apps/wbi_nwt
        push: true
        tags: ghcr.io/predictiveecology/wbi_shiny/shiny-wbi_nwt:v2

  build-and-push-wbi:
    name: Build and Push Docker Image for WBI NWT Shiny App
    if: "contains(github.event.head_commit.message, 'build wbi')"
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Build and push'
      uses: docker/build-push-action@v4
      with:
        context: ./03-apps/wbi
        push: true
        tags: ghcr.io/predictiveecology/wbi_shiny/shiny-wbi:v1
