name: WBI App

on:
  push:
    branches: [ "main" ]
    paths: [ "03-apps/wbi/**"]
  pull_request:
    branches: [ "main" ]
    paths: [ "03-apps/wbi/**"]

permissions:
  contents: read

jobs:
  rcmdcheck:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps("03-apps/wbi", dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck("03-apps/wbi", args = "--no-manual", error_on = "error")
        shell: Rscript {0}